/*

 OVERWORLD_MAP_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 36
   Tile set      : C:\Users\sacha_v0bdq8d\OneDrive\Documents\Programmation\C_CPP\PROJECTS\GB_dev\poke_project_v1\asset\backgrounds\over_world_1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define overworld_map_1Width 40
#define overworld_map_1Height 36
#define overworld_map_1Bank 0

extern unsigned char overworld_map_1[];

/* End of OVERWORLD_MAP_1.H */
