/*

 SPRITE_1.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char sprite_1[] =
{
  // tile 1
  0x7E,0x7E,0xBD,0xC3,0xC3,0xFF,0xFF,0xBD,
  0xDB,0xA5,0xFF,0xA5,0x66,0x5A,0x3C,0x3C,

  // tile 2
  0x7E,0x7E,0x89,0xF7,0xC3,0xBD,0xBD,0xFF,
  0xFF,0xC3,0xFF,0xA5,0x7E,0x42,0x3C,0x3C
};

/* End of SPRITE_1.C */
